### PR TITLE
Fix absolute paths

### LINKED ISSUE #191: grunt-contrib-cssmin creating min.css empty files
I have the following configuration with the cssmin version 0.12.2:

```js
cssmin: {
      target: {
        files: [{
          expand: true,
          cwd: css_dir,
          src: ['**/*.css',  '**/!*.min.css'],
          dest: css_dir,
          ext: '.min.css'
        }]
      }
    },
```
I am runnit this grunt task with ANT,

When i execute the tasks the result is:

[exec] ←[4mRunning "cssmin:target" (cssmin) task←[24m
[exec] ←[32mDone, without errors.←[39m

And the output directory has the .min.css files but those files are all empty.
The same configuration with css-min version 0.11.0 works correctly. There is a problem between 0.11.0 and 0.12.2.

The complete explanation of the problem is here:
https://github.com/jakubpawlowicz/clean-css/issues/467

### PR DESCRIPTION
**Pull request by smcgivern**
This should fix #191 and maybe #196 too.

The `relativeTo` option was removed at https://github.com/gruntjs/grunt-contrib-cssmin/pull/170/files#diff-f0ee9eb300066e1e51fcfbad9d7a78e1L45 and seemingly never added back.

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -1,4 +1,7 @@
 'use strict';
+function absolutePath(path) {
+  return __dirname + '/' + path;
```
Comment (sindresorhus) [inline Gruntfile.js]: Should use `path.join()`.

File: tasks/cssmin.js [hunk 2]
```diff
@@ -34,6 +34,11 @@ module.exports = function (grunt) {
 
       options.target = file.dest;
 
+      var unCompiledCssString = availableFiles.map(function (file) {
+        options.relativeTo = path.dirname(file);
```
Comment (sindresorhus) [inline tasks/cssmin.js]: No point in doing this inside the iteration as it will only overwrite for each file. You can just set it outside using `file[0]` with the same effect.

**Comment by smcgivern** [comment]
Good points. Do you mind if I just amend the existing commit, or would you prefer a separate one?

**Comment by XhmikosR** [comment]
@smcgivern: just amend.

**Comment by smcgivern** [comment]
OK, done :+1:

**Comment by jd-carroll** [comment]
I know this is already merged, but..

Why are you setting:

    options.relativeTo = path.dirname(availableFiles[0]);

When it should be relative to the destination:

    options.relativeTo = options.target = file.dest;

**Comment by smcgivern** [comment]
Honestly, because it was like that before: https://github.com/gruntjs/grunt-contrib-cssmin/blob/4af3941b3b3168c29f58bb611e5b4deb897a7ee8/tasks/cssmin.js#L45 In the case here, where we're using absolute paths, it doesn't look like it matters. A test case that shows why this is the wrong behaviour is probably the best thing to provide.

This also isn't merged - @XhmikosR a little help please? :smiley:
